# Generated by Django 5.2.2 on 2025-06-13 06:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='purpose',
            field=models.CharField(choices=[('main', 'Main (一覧用メイン画像)'), ('detail', 'Detail (詳細画面用画像)'), ('detail_main', 'Detail Main (詳細画面用メイン画像)'), ('author', 'Author (制作者の顔写真)'), ('software', 'Software (使用ソフトのアイコン)')], max_length=20, verbose_name='Purpose'),
        ),
    ]
