# Generated by Django 5.2.2 on 2025-06-13 06:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_image_options_remove_image_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=core.models.image_upload_path),
        ),
    ]
