# Generated by Django 5.2.2 on 2025-06-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='work',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
